version: '3.1'

services:
  mysql-dev:
    image: mysql_docker 
    command: --default-authentication-plugin=mysql_native_password
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/docker/data:/var/lib/mysql
    ports:
      - "3308:3306"
